### ISSUE TITLE
Feature request: using docker and build the docker into docker-hub

### ISSUE THREAD

**Issue by modaresimr** [roborescue/rcrs-server#55]
I think it can be interesting to use docker and Gradle alpine image ([gradle:jdk17-alpine](https://hub.docker.com/_/gradle?tab=description&page=1&name=alp) ~~or openjdk:17-jdk-alpine~~)
In this case, it can be easier for some newcomers to start using the ADF and also the simulator.

each time they can easily run the code by 
```docker-compose up```

**Comment by gnardin** [comment]
@modaresimr 
Can you please specify where this setting should be included?
Thank you,

**Comment by modaresimr** [comment]
We have a source-code dir, kernel, web-viewer 
therefore our docker-compose file can be:
```
version: '3.3'
services:
    kernel:
        volumes:
            - ./kernel-logs:/logs
            - ./maps:/maps
        env_file: rcrs.env
        image: roborescue:rcrs-server
    web_viewer:
        depends_on: kernel
        image: roborescue:rcrs-web-viewer
    agent_code:
        depends_on: kernel
        env_file: rcrs.env
        volumes:
            - ./agent:/agent' 
            - ./agent-logs:/logs
        image: roborescue:rcrs-adf-core
```

it will fetch the sample code and maps if the directory is empty, compile the code and kernel, and run the kernel depending on the mode then wait until the kernel is ready and start the agent

if the RUN_MODE is precompute+fullrun it will run in precompute mode then kill the kernel and run it in fullrun mode.

It can be much easier even for the experienced users of our league. 

        env_file: rcrs.env
```
RUN_MODE=fullrun_only # precompute+fullrun, precomute_only, fullrun_only
MAP=paris
....
```

A more complex situation can be prepared to run in swarm mode over multiple computers
